### ISSUE TITLE
Nonstandard workspace folder

### ISSUE THREAD

**Issue by Soundbytes** [hengsin/idempiere-oomph#2]
@hengsin This is rather a question and not really an issue. (At least I hope so).
After running the installer I found that the eclipse workspace is the parent folder of the idempiere source code directory and  not the iDempiere folder itself.
This setup is different from the one advised in the iDempiere development tutorial in the wiki.
(https://wiki.idempiere.org/en/Setting_up_Eclipse) where the idempiere source code folder is used as the workspace directory.
While it works just fine (I did use that setup myself when I started iDempiere development) I think it can lead to some irritation because People can get confused when they  try to follow the Plugin Development tutorials using an IDE created with the installer. All the Tutorials in the wiki refer to the 'canonical' workspace path. Some tutorials also show path settings in eclipse dialogs that are relative to the workspace directory. Each of these also would need to have a comment added that explains the different workspace settings in manual and installer created IDE setups.
Can you comment on the reasoning behind the decision to use a different workspace setup? 
Thanks

**Comment by hengsin** [comment]
The usual practice is not to use your source folder as Eclipse workspace since that will create lots of Eclipse stuff that you have no intention to keep in your git repository. Also, that means you can't easily copy or move your source folder to a different workspace.

The reason that approach is use in the link you mention is not that we wanted to but it is because before some recent changes, it only work if you use your source folder as the Eclipse workspace.

**Comment by Soundbytes** [comment]
Thanks for the clarification. But why do you say it is not the usual practice when all available documentation as well as numerous forum posts from the past advise one to do just that? From my experience it really is the other way round. IMO this change really should have been communicated more prominently because to me at least this is absolute news.

**Comment by hengsin** [comment]
My usual practice above is not referring specifically to iDempiere but the common practice of setting up Eclipse workspace.

**Comment by hengsin** [comment]
As for past advise and forum posts, as I've mention above, using the iDempiere source folder as Eclipse workspace is the only working way prior to the changes make for the oomph related ticket (You can't say that's an advise for best practice when that's the only way it will work).

**Comment by Soundbytes** [comment]
I see. I really do not criticize the decision to improve the workspace setup and I also recognize the constraints that have lead to the nonstandard setup in the past. My problem is that this important information has not reached me earlier. 
I will surely monitor the jira task list a bit more intensively in the future. Still I would appreciate it if these kind of changes could be also announced in the forum every now and then. Thanks!

**Comment by hengsin** [comment]
alright, agree we can communicate better on this one.

It is not really that critical though, the existing approach of using iDempiere source folder still works fine as before and in fact, my own local setup is still using the old approach.

**Comment by hengsin** [comment]
btw, should add that it is tricky to get the oomph installer to works with iDempiere source folder as Eclipse workspace and that leads to the changes to make this more flexible, i.e you can use have Eclipse workspace inside or outside of the iDempiere source folder (this flexbility is actually a FR that have been requested before).
