### ISSUE TITLE
Eclipse 2021-03 comes with a Java 15 JRE preconfigured 

### ISSUE THREAD

**Issue by Soundbytes** [hengsin/idempiere-oomph#4]
I just installed the IDE and workspace from scratch and found that iDempiere won't build right out of the box. The reason was that Eclipse came with the java 15 JRE preconfigured and iDempiere don't like that. 
I was able to work around the issue by manually configuring the required java 11 JRE.

**Comment by hengsin** [comment]
are you using the installer from the "releases" here ? The installer should use jdk11 instead of jdk15.

**Comment by Soundbytes** [comment]
OK, Thanks for the quick answer. I had set SETUP_DB to false in setup.sh. otherwise I don't remember having changed anything else about the configuration.
The Install process then stopped right after the eclipse installation. I wonder why the eclipse configuration step was skipped then.

**Comment by hengsin** [comment]
sounds like you have posted question to the wrong repository ...

**Comment by Soundbytes** [comment]
Oops, you are right!

$ git remote -v
origin	https://github.com/hengsin/idempiere-dev-setup.git (fetch)
origin	https://github.com/hengsin/idempiere-dev-setup.git (push)

**Comment by hengsin** [comment]
if needed, please move this to the idempiere-dev-setup repo.
